Create send_batch_data method
adafruit/Adafruit_CircuitPython_AdafruitIO pull request #70
Opened 2021-04-30 14:02 UTC by rodrigoargumedo

This would allow CircuitPython to send batch array of data that can be created from all available devices to the Adafruit.IO service. I will require further testing in all of my CircuitPython devices in the coming weeks and will mark this for review once it is complete.

2021-04-30 18:17 UTC, rodrigoargumedo commented
I'm not sure why the pre-commit hook is failing when they are all passing, but I'm looking into it why is it not passing.

2021-05-03 13:19 UTC, brentru commented
@rodrigoargumedo  This is marked as a draft PR - is it ready for review yet? What's blocking it?

2021-05-03 14:12 UTC, rodrigoargumedo commented
@brentru The only code block is the unexpected JSON parsing error when I tested it with my Matrix Portal. It sounded pretty odd, but I was expecting something a value would be sent to the service itself.

2021-05-03 14:23 UTC, rodrigoargumedo commented
I may believe that I incorrectly put the POST method instead of directing the `send_data` method, which could've been expected.

2021-05-04 00:51 UTC, rodrigoargumedo commented
I found the solution and getting some more tests readying up soon.

2021-05-04 01:37 UTC, rodrigoargumedo commented
Now, I am ready for code review.

2021-05-05 15:09 UTC, brentru commented
@rodrigoargumedo  Could you post an example `code.py` that you're using to test this with so I can see how this function would be implemented?

2021-05-05 15:11 UTC, brentru requested changes

2021-05-05 15:11 UTC, brentru commented on adafruit_io/adafruit_io.py
> +        :param list Data: Data list to send
The kwarg on L568 is called `data_list`, this line should be `:param list data_list`.

2021-05-05 15:11 UTC, brentru commented on adafruit_io/adafruit_io.py
> +        :param str feed_key: Adafruit IO feed key
The kwarg should be changed to `feed_key` on L568 to match the other method signatures.

2021-05-05 18:44 UTC, rodrigoargumedo commented
I'll do those changes tonight and push them. Thanks! 👍

2021-05-06 13:20 UTC, brentru approved these changes

2021-05-06 13:20 UTC, brentru commented
Thanks for making these changes.

2021-05-06 13:20 UTC, merged